[package]
name = "pinkprose-id"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
crossbeam-channel = { workspace = true }
rand = { workspace = true }
spin_sleep = { workspace = true }
