[workspace]
resolver = "2"
members = [
	# "packages/api",
	# "packages/auth",
	# "packages/auth-old",
	"packages/backend",
	# "packages/db/connector",
	# "packages/db/server",
	"packages/frontend",
	# "packages/id",
	"packages/model"
]

[profile.wasm-release]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[workspace.dependencies.actix-files]
version = "0.6.5"

[workspace.dependencies.actix-web]
version = "4.5.1"

[workspace.dependencies.anyhow]
version = "1.0.81"

[workspace.dependencies.argon2]
version = "0.5.3"

[workspace.dependencies.blake3]
version = "1.5.1"

[workspace.dependencies.chacha20poly1305]
version = "0.10.1"

[workspace.dependencies.chrono]
version = "0.4.35"

[workspace.dependencies.console_error_panic_hook]
version = "0.1.7"

[workspace.dependencies.constant_time_eq]
version = "0.3.0"

[workspace.dependencies.crossbeam-channel]
version = "0.5.12"

[workspace.dependencies.getrandom]
version = "0.2.12"

[workspace.dependencies.http]
version = "1.1.0"

[workspace.dependencies.leptos]
version = "0.6.9"
features = ["nightly"]

[workspace.dependencies.leptos_actix]
version = "0.6.9"

[workspace.dependencies.leptos_meta]
version = "0.6.9"
features = ["nightly"]

[workspace.dependencies.leptos_router]
version = "0.6.9"
features = ["nightly"]

[workspace.dependencies.p384]
version = "0.13.0"

[workspace.dependencies.rand]
version = "0.8.5"

[workspace.dependencies.serde]
version = "1.0.197"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1.0.114"

[workspace.dependencies.spin_sleep]
version = "1.2.0"

[workspace.dependencies.surrealdb]
version = "1.3.0"
default-features = false

[workspace.dependencies.thiserror]
version = "1.0.58"

[workspace.dependencies.tokio-tungstenite]
version = "0.21.0"
features = ["rustls-tls-webpki-roots"]

[workspace.dependencies.validator]
version = "0.17.0"

[workspace.dependencies.wasm-bindgen]
version = "0.2.92"

[workspace.dependencies.wasm-bindgen-futures]
version = "0.4.42"

[workspace.dependencies.web-sys]
version = "0.3.69"

[workspace.dependencies.wiwi]
version = "0.5.3"
features = ["hex", "z85"]

[workspace.dependencies.zeroize]
version = "1.7.0"
