[workspace]
resolver = "2"
members = [
	"packages/api",
	"packages/auth",
	"packages/auth-old",
	"packages/db/connector",
	"packages/db/server",
	"packages/frontend",
	"packages/id",
	"packages/model"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[workspace.dependencies]
actix-web = "4.5.1"
bitcode = "0.6.0"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
