[workspace]
resolver = "2"
members = [
	"packages/backend"
]

[profile.wasm-release]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[workspace.dependencies.actix-web]
version = "4.5.1"

[workspace.dependencies.anyhow]
version = "1.0.81"
