[package]
name = "pinkprose-db-server"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
serde = { workspace = true }
surrealdb = { workspace = true }
thiserror = { workspace = true }

[features]
db-dev = ["surrealdb/kv-speedb"]

default = ["db-dev"]
