[package]
name = "pinkprose-db-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde.workspace = true
surrealdb = { version = "1.3.0", default-features = false }
thiserror.workspace = true

[features]
db-dev = ["surrealdb/kv-speedb"]

default = ["db-dev"]
