[package]
name = "pinkprose-api"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
bitcode = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

[features]
client = [
	"dep:wasm-bindgen-futures",
	"dep:web-sys",

	# for things like window.fetch etc
	"web-sys/Window"
]

server = []

default = ["client", "server"]
