[package]
name = "pinkprose-model"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
bitcode = { workspace = true }
serde = { workspace = true }
