[package]
name = "pinkprose-db-connector"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
tokio-tungstenite = { workspace = true }

[features]
