[package]
name = "pinkprose-frontend"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
actix-files = { workspace = true, optional = true }
actix-web = { workspace = true, optional = true }
anyhow = { workspace = true }
console_error_panic_hook = { workspace = true, optional = true }
# http = { workspace = true, optional = true }
leptos = { workspace = true }
leptos_actix = { workspace = true, optional = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
# pinkprose-api = { workspace = true }
pinkprose-auth = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }

[features]
hydrate = [
	"dep:console_error_panic_hook",
	"dep:wasm-bindgen",
	"leptos/hydrate",
	"leptos_meta/hydrate",
	"leptos_router/hydrate",
	# "pinkprose-auth/client"
]
ssr = [
	"dep:actix-files",
	"dep:actix-web",
	"dep:leptos_actix",
	"leptos/ssr",
	"leptos_meta/ssr",
	"leptos_router/ssr",
	# "pinkprose-auth/server"
]

[package.metadata.leptos]
site-root = "target/site-build"
site-pkg-dir = "lgpa__"
assets-dir = "assets"
site-addr = "127.0.0.1:3000"
reload-port = 3001
browserquery = "fully supports wasm"
watch = false
env = "DEV" # ????????????
bin-features = ["ssr"]
lib-features = ["hydrate"]
lib-profile-release = "wasm-release"

[lib]
crate-type = ["cdylib", "rlib"]
