[package]
name = "pinkprose-frontend"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
actix-files = { version = "0.6.5", optional = true }
actix-web = { version = "4.5.1", optional = true }
anyhow = "1.0.81"
console_error_panic_hook = { version = "0.1.7", optional = true }
http = { version = "1.1.0", optional = true }
leptos = { version = "0.6.9", features = ["nightly"] }
leptos_actix = { version = "0.6.9", optional = true }
leptos_meta = { version = "0.6.9", features = ["nightly"] }
leptos_router = { version = "0.6.9", features = ["nightly"] }
pinkprose-api = { path = "../api" }
pinkprose-auth = { path = "../auth" }
wasm-bindgen = "0.2.92"

[features]
hydrate = [
	"dep:console_error_panic_hook",
	"leptos/hydrate",
	"leptos_meta/hydrate",
	"leptos_router/hydrate",
	"pinkprose-auth/client"
]
ssr = [
	"dep:actix-files",
	"dep:actix-web",
	"dep:leptos_actix",
	"leptos/ssr",
	"leptos_meta/ssr",
	"leptos_router/ssr",
	"pinkprose-auth/server"
]

[package.metadata.leptos]
site-root = "target/site-build"
site-pkg-dir = "lgpa__"
assets-dir = "assets"
site-addr = "127.0.0.1:3000"
reload-port = 3001
browserquery = "fully supports wasm"
watch = false
env = "DEV" # ????????????
bin-features = ["ssr"]
lib-features = ["hydrate"]
lib-profile-release = "wasm-release"

[lib]
crate-type = ["cdylib", "rlib"]
