[application]
name = "pink-prose"
default_platform = "fullstack"
out_dir = "../../target/dioxus"
asset_dir = "assets"

[web.app]
title = "Pink Prose"

[web.watcher]
reload_html = true
watch_path = ["src", "../../target/dioxus/css.css"]

[web.resource]
style = ["css.css"]
script = []

[web.resource.dev]
script = []
