[package]
name = "pink-prose"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
actix-files = { workspace = true, optional = true }
actix-web = { workspace = true, optional = true }
anyhow = { workspace = true }
catppuccin = { workspace = true }
http = { workspace = true, optional = true }
leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_actix = { workspace = true, optional = true }
leptos_router = { workspace = true }
pink-prose-db = { workspace = true, optional = true }
serde = { workspace = true }
wasm-bindgen = { workspace = true }
urlencoding = { workspace = true }
web-sys = { workspace = true, features = ["Storage", "Window"] }
wiwi = { workspace = true, features = ["rand", "z85"] }

[features]
hydrate = [
	"leptos/hydrate",
	"leptos_meta/hydrate",
	"leptos_router/hydrate"
]
ssr = [
	"dep:actix-files",
	"dep:actix-web",
	"dep:http",
	"dep:leptos_actix",
	"dep:pink-prose-db",
	"leptos/ssr",
	"leptos_meta/ssr",
	"leptos_router/ssr"
]

[package.metadata.leptos]
site-root = "target/site-build"
site-pkg-dir = "-"
style-file = "../../target/unoptimised.css"
assets-dir = "assets"
site-addr = "127.0.0.1:3000"
reload-port = 3001
browserquery = "supports wasm"
# The environment Leptos will run in, usually either "DEV" or "PROD"
# ??
env = "DEV"
bin-features = ["ssr"]
lib-features = ["hydrate"]
lib-profile-release = "wasm-release"
