[package]
name = "pinkprose-backend"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
