[package]
name = "pinkprose-auth-2"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
argon2 = "0.5.3"
blake3 = "1.5.1"
chacha20poly1305 = "0.10.1"
constant_time_eq = "0.3.0"
getrandom = "0.2.12"
p384 = "0.13.0"
rand = "0.8.5"
thiserror.workspace = true
validator = "0.17.0"
wiwi = { version = "0.5.0", features = ["z85"] }
zeroize = "1.7.0"

[features]
client = ["getrandom/js"]
server = []
