[package]
name = "pink-prose-db"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
surrealdb = { workspace = true }
thiserror = { workspace = true }

[features]
