[package]
name = "pink-prose-db"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
parking_lot = { workspace = true }
surrealdb = { workspace = true }
thiserror = { workspace = true }
wiwi = { workspace = true, features = ["id-unstable"] }

[features]
