[package]
name = "nameplaceholder-db"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde.workspace = true
surrealdb = { version = "1.3.0", default-features = false, features = ["kv-speedb", "kv-tikv"] }
thiserror = "1.0.58"
