[package]
name = "pinkprose-auth-old"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
argon2 = "0.5.3"
blake3 = "1.5.1"
chacha20poly1305 = "0.10.1"
constant_time_eq = "0.3.0"
getrandom = "0.2.12"
hex = "0.4.3"
p384 = "0.13.0"
rand.workspace = true
thiserror.workspace = true
validator = "0.17.0"

[features]
client = ["getrandom/js"]
server = []
