[package]
name = "pinkprose-auth-old"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
argon2 = { workspace = true }
blake3 = { workspace = true }
chacha20poly1305 = { workspace = true }
constant_time_eq = { workspace = true }
getrandom = { workspace = true }
p384 = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
validator = { workspace = true }
wiwi = { workspace = true }

[features]
# move getrandom/js to its own feature?? cause not all clients are js
# client = ["getrandom/js"]
# server = []
